name: CI/CD Pipeline for Backend

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd /path/to/your/repo  # Update with the actual path of your repo on the runner
          npm install

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@your_ec2_ip 'cd /path/to/your/repo && git pull origin main && npm install && pm2 restart your-app-name || pm2 start your-app-name --name your-app-name'
