name: CI/CD Pipeline for Backend

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd ~/actions-runner/_work/yham-server/yham-server  
          npm install

      - name: Stop Existing PM2 Process
        run: |
          pm2 stop backend-api || echo "PM2 process 'backend-api' not running, nothing to stop"

      - name: Start Server with PM2
        run: |
          cd ~/actions-runner/_work/yham-server/yham-server 
          npm run pm2-start --name backend-api --time

      - name: Save PM2 Process List
        run: |
          pm2 save  # Save the PM2 process list so it's restarted on reboot

      - name: Verify PM2 Status
        run: |
          pm2 status  # Optional: Check if PM2 is running correctly
