name: CI/CD Pipeline for Backend

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd ~/actions-runner/_work/yham-server/yham-server  # Corrected path
          npm install

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-209-160-201.compute-1.amazonaws.com '
            cd ~/actions-runner/_work/yham-server/yham-server && \
            git pull origin main && \
            npm install && \
            pm2 startOrRestart ecosystem.config.js --env production
          '
